from __future__ import annotations

import re
from datetime import datetime, timezone

from app.analyzer.russian_post import build_rule_based_russian_post
from app.models import FetchedItem, Source
from app.utils.text import normalize_text


PROMO_PATTERNS = [
    "промокод",
    "скидка",
    "sponsored",
    "advertisement",
    "партнерский",
    "affiliate",
    "apply now",
    "applications close",
    "register now",
    "early bird",
    "save your spot",
    "secure your shot",
    "startup battlefield",
]
JOB_PATTERNS = ["вакансия", "hiring", "we are hiring", "job opening", "career"]
CLICKBAIT_PATTERNS = ["срочно", "шок", "уничтожит", "взорвет", "🔥", "!!!", "никогда не будет прежним"]
LISTICLE_PATTERNS = ["топ-", "top ", "weekly roundup", "дайджест", "подборка"]
TOOL_PATTERNS = ["api", "tool", "инструмент", "sdk", "open-source", "github", "библиотека"]
IMPACT_PATTERNS = ["regulation", "lawsuit", "ban", "acquires", "funding", "рынок", "бизнес", "разработчик"]
UPDATE_PATTERNS = ["update", "обнов", "feature", "функц", "preview", "beta"]
MODEL_PATTERNS = ["model", "модель", "gpt", "claude", "gemini", "llama", "mistral", "deepseek"]
BROAD_SOURCE_CATEGORIES = {"tech_community"}
RELEVANCE_BOILERPLATE_PATTERNS = [
    "Read AI-generated summary",
    "AI-generated summary",
    "Summaries were generated by Google AI",
    "Generative AI is experimental",
]


def _contains_any(text: str, patterns: list[str]) -> bool:
    lowered = text.lower()
    return any(pattern.lower() in lowered for pattern in patterns)


def _keyword_hits(text: str, keywords: list[str]) -> bool:
    lowered = text.lower()
    return any(keyword.lower() in lowered for keyword in keywords)


def _strip_relevance_boilerplate(text: str) -> str:
    cleaned = text or ""
    for pattern in RELEVANCE_BOILERPLATE_PATTERNS:
        cleaned = re.sub(re.escape(pattern), " ", cleaned, flags=re.IGNORECASE)
    return normalize_text(cleaned)


def _age_score(published_at: datetime | None, now: datetime) -> int:
    if not published_at:
        return 5
    if published_at.tzinfo is None:
        published_at = published_at.replace(tzinfo=timezone.utc)
    age = now - published_at
    if age.total_seconds() < 24 * 3600:
        return 15
    if age.days < 3:
        return 10
    if age.days < 7:
        return 5
    return 0


def calculate_score(
    item: FetchedItem,
    source: Source,
    ai_keywords: list[str],
    important_keywords: list[str],
    *,
    now: datetime | None = None,
) -> tuple[int, list[str], list[str]]:
    now = now or datetime.now(timezone.utc)
    title = item.title or ""
    text = item.raw_text or ""
    relevance_text = _strip_relevance_boilerplate(text)
    combined_for_relevance = f"{title} {relevance_text}"
    combined = f"{title} {text}"
    reasons: list[str] = []
    penalties: list[str] = []

    title_hit = _keyword_hits(title, ai_keywords)
    text_hit = _keyword_hits(relevance_text, ai_keywords)
    if title_hit and text_hit:
        relevance = 25
    elif title_hit:
        relevance = 15
    elif text_hit:
        relevance = 10
    elif _contains_any(combined_for_relevance, ["startup", "technology", "automation", "robot", "software", "it"]):
        relevance = 5
    else:
        relevance = 0
    reasons.append(f"relevance={relevance}")

    important_hit = _keyword_hits(combined, important_keywords)
    if source.tier == 1 and important_hit and _contains_any(combined, MODEL_PATTERNS + ["api", "research"]):
        importance = 25
    elif important_hit:
        importance = 20
    elif _contains_any(combined, UPDATE_PATTERNS):
        importance = 10
    elif relevance:
        importance = 5
    else:
        importance = 0
    reasons.append(f"importance={importance}")

    novelty = _age_score(item.published_at, now)
    reasons.append(f"novelty={novelty}")

    specificity = 0
    if re.search(r"\b[A-Z][A-Za-z0-9.-]{2,}\b", title):
        specificity += 5
    if important_hit or _contains_any(combined, UPDATE_PATTERNS + MODEL_PATTERNS):
        specificity += 5
    if re.search(r"\d|GPT|Claude|Gemini|Llama|API|v\d|2\.|3\.|4\.", combined, re.IGNORECASE):
        specificity += 5
    reasons.append(f"specificity={specificity}")

    trust = max(0, min(source.trust_score, 10))
    reasons.append(f"trust={trust}")

    audience = 0
    if _contains_any(combined, TOOL_PATTERNS):
        audience += 5
    if _contains_any(combined, ["viral", "trend", "breakthrough", "chatgpt", "openai", "google", "nvidia"]):
        audience += 3
    if _contains_any(combined, IMPACT_PATTERNS):
        audience += 2
    reasons.append(f"audience={audience}")

    score = relevance + importance + novelty + specificity + trust + audience

    lowered = combined.lower()
    if _contains_any(lowered, PROMO_PATTERNS):
        score -= 30
        penalties.append("ad_or_partner_material")
    if _contains_any(lowered, JOB_PATTERNS):
        score -= 25
        penalties.append("job_post")
    if _contains_any(lowered, LISTICLE_PATTERNS) and not important_hit:
        score -= 20
        penalties.append("roundup_without_clear_news")
    if len(normalize_text(text)) < 120:
        score -= 20
        penalties.append("too_short_without_facts")
    if _contains_any(lowered, CLICKBAIT_PATTERNS):
        score -= 15
        penalties.append("clickbait")
    if not item.url:
        score -= 50
        penalties.append("missing_source_url")
    if source.category in BROAD_SOURCE_CATEGORIES and not title_hit:
        score -= 35
        penalties.append("weak_relevance_for_broad_source")

    return max(0, min(100, score)), reasons, penalties


def build_telegram_post(item: FetchedItem, source: Source, cleaned_text: str, score: int) -> str:
    return build_rule_based_russian_post(item, source, cleaned_text, score)


def _why_it_matters(text: str, score: int) -> str:
    lowered = text.lower()
    if score < 70:
        return ""
    if _contains_any(lowered, ["api", "tool", "sdk", "open-source", "github"]):
        return "Такие обновления быстро превращаются в рабочие инструменты для разработчиков и команд, а не остаются новостью только для обсуждения."
    if _contains_any(lowered, ["funding", "raises", "acquires", "investment", "инвестиции", "сделка"]):
        return "Деньги и сделки показывают, какие направления AI и технологий рынок считает перспективными."
    if _contains_any(lowered, ["regulation", "lawsuit", "ban", "регулирование", "запрет"]):
        return "Регулирование и судебные решения могут менять правила работы для компаний, разработчиков и пользователей."
    if _contains_any(lowered, MODEL_PATTERNS):
        return "Новые модели и API влияют на то, какие продукты можно собрать быстрее, дешевле или качественнее."
    return ""
